[tool.poetry]
name = "tom-demo"
version = "0.0.0"  # version supplied by poetry-dynamic-versioning
description = "A Demonstration TOM hosted at http://tom-demo.lco.global"
authors = ["TOM Toolkit Project"]
maintainers = ["Joey Chatelain <jchate6@gmail.com>",
    "William Lindstrom <llindstrom@lco.global>",
    "Rachel Street <rstreet@lco.global>"
]
readme = "README.md"
license = "GPL-3.0-only"
homepage = "http://tom-demo.lco.global"
repository = "https://github.com/LCOGT/tom-demo"
packages = [{include = "tom_demo"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
tomtoolkit = "^2.18.5"
tom-hermes = "^0.1.10"
whitenoise = "6.6"
crispy-bootstrap4 = "^2024.1"
tom-alertstreams = "^0.6.2"
psycopg2-binary = "^2.9.9"
django-cors-headers = "^4.3.1"
django-webpack-loader = "^3.1.0"
gunicorn = {extras = ["gevent"], version = "^22.0.0"}
tom-swift = "^0.2.1"
tom-tns = "^0.2.2"
tom-fink = "^0.6.2"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
# the default pattern regex makes the 'v' manditory
# this pattern modifies the default regex in order to make the 'v' optional
# ('v' becomes '[v]?' meaning a single v, [v], and ? means optional)
pattern = "(?x)^[v]?((?P<epoch>\\d+)!)?(?P<base>\\d+(\\.\\d+)*)([-._]?((?P<stage>[a-zA-Z]+)[-._]?(?P<revision>\\d+)?))?(\\+(?P<tagged_metadata>.+))?$"

# substitute version not only in pyproject.toml (which the config block above does)
# but also the __version__.py file
[tool.poetry-dynamic-versioning.substitution]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
