apiVersion: v1
appVersion: "0.0.0" # altered to be the git tag (if there is one) or  git commit SHA ID
description: A Helm chart for the TOM Toolkit demostration TOM
name: tom-demo
version: 0.4.0 # will be appended with -${git-commit-id}
