apiVersion: v1
 # altered to be the git tag (if there is one) or  git commit SHA ID
appVersion: "0.0.0"
description: A Helm chart for the TOM Toolkit demostration TOM
name: tom-demo
version: 0.5.0 # will be appended with -${git-commit-id}
