# Helm chart values for Production Deployment

debug: "False"

replicaCount: 1

resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
  hosts:
    - host: tom-demo.lco.global
      paths:
        - "/"