# Helm chart values for Production Deployment

replicaCount: 2

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 1000m
    memory: 256Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-private
  hosts:
    - host: tom-demo.lco.gtn
      paths:
        - "/"