apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tom-demo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tom-demo.name" . }}
    helm.sh/chart: {{ include "tom-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

# write URL dictionary below to urls.json upon install
data:
  urls.json: |
    {
      "tomDemoApiUrl": {{ include "tom-demo.mainDeployUrl" . | quote }}
    }
  TOM_DEMO_TEST_API_URL: http://tom-demo-dev.lco.gtn
