apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tom-demo.fullname" . }}-ingester
  labels:
{{ include "tom-demo.labels" . | indent 4 }}
    app.kubernetes.io/component: "ingester"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tom-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "ingester"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tom-demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "ingester"
    spec:
      initContainers:
        # wait for database to become ready
        - name: check-db-ready
          image: "postgres:11.2-alpine"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - >
              until pg_isready \
                  --username={{ .Values.postgresql.auth.username | quote }} \
                  --dbname={{ .Values.postgresql.auth.database | quote }} \
                  --host={{ include "tom-demo.dbhost" . | quote }} \
                  --port={{ .Values.postgresql.primary.service.port.postgresql | quote }};
                do echo waiting for database;
                sleep 2;
                done;
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 50m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 16Mi
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "tom-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ingester
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python
            - manage.py
#            - readstreams
          env:
            {{ include "tom-demo.extraEnv" . | nindent 12 }}
            {{ include "tom-demo.backendEnv" . | nindent 12 }}
          envFrom:
            - secretRef:
                name: tom-demo-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp-ingester
              mountPath: /tmp
              readOnly: false
      volumes:
        - name: app-configuration
          configMap:
            name: {{ include "tom-demo.fullname" . }}
        - name: tmp-ingester
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
        - name: specutils
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
        - name: astropy
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
